### ISSUE TITLE
Nueva vista del Focus Mode cuenta atrás

### ISSUE THREAD

**Issue by alejbormeg** [SergioQuijanoRey/AgilUGR#42]
Hay que hacer una nueva vista para el Focus Mode para mejorar la estética de la app

**Comment by alejbormeg** [comment]
@alejbormeg Después de esto me pongo con sensores

**Comment by BlancaCC** [comment]
@alejbormeg Gracias Alex, eres más apañao que las pesetas en tiempos de las pesetillas. 😭

**Comment by alejbormeg** [comment]
Vista acabada
